server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:

  - url: http://loki-ip-address:3100/loki/api/v1/push
    backoff_config:
      min_period: 2s
      max_period: 1h
    batchsize: 100
scrape_configs:
  - job_name: system
    static_configs:
    - targets:
       - target-ip-address
      labels:
         job: logs_target
         __path__: /var/log/*log
